export default {
    code: 0,
    message: 'SUCCESS',
    detail: null,
    timestamp: 1615169866412,
    data: {
        pageNum: 1,
        pageSize: 10,
        size: 10,
        startRow: 1,
        endRow: 10,
        total: 46,
        pages: 5,
        list: [
            {
                id: 6,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-13 15:34:36',
                modifiedTime: '2021-01-20 10:50:49',
                deleted: false,
                number: '00006',
                designerCode: 'DN_2021011300005',
                designerName: '黎易来',
                designerHeadImg: 'https://res1.bnq.com.cn/25b70d71286c4ef9bc4837db3dcc2cbb.jpg',
                caseTitle: '极简线条+艺术灯',
                serviceType: 'DST10003',
                serviceTypeName: '全案设计',
                caseHouseType: '1003',
                caseHouseTypeName: '三室',
                room: 3,
                hall: 1,
                kitchen: 1,
                toilet: 2,
                caseSize: 136.0,
                designStyle: 'tc31002,tc31007,tc31016',
                caseCostType: null,
                totalCost: null,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21007,tc21001,tc21006',
                ownerImage: 'tc11005,tc11015',
                caseProvinceCode: '310000',
                caseProvinceName: '上海',
                caseCityCode: '310000',
                caseCityName: null,
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 28.0,
                qrCode: 'https://res1.bnq.com.cn/FgYmAffNXjq86Ikz9VSki8dXlJ0p',
                coverImg: 'https://res1.bnq.com.cn/2eaab5fa71964bb38722c87ef8683c3c.jpg',
                readCount: 17,
                shareCount: 17,
                keyword: 'keyword666',
                imgWidth: 2775,
                imgHeight: 1852,
            },
            {
                id: 38,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-20 19:01:39',
                modifiedTime: '2021-01-20 19:01:40',
                deleted: false,
                number: '00038',
                designerCode: 'DN_2021011300005',
                designerName: '黎易来',
                designerHeadImg: 'https://res1.bnq.com.cn/25b70d71286c4ef9bc4837db3dcc2cbb.jpg',
                caseTitle: '160㎡天空之镜，以自然之名',
                serviceType: 'DST10003',
                serviceTypeName: '全案设计',
                caseHouseType: '1002',
                caseHouseTypeName: '两室',
                room: 2,
                hall: 2,
                kitchen: 1,
                toilet: 2,
                caseSize: 160.0,
                designStyle: 'tc31002',
                caseCostType: null,
                totalCost: null,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: '',
                caseProvinceCode: '310000',
                caseProvinceName: '上海',
                caseCityCode: '310000',
                caseCityName: null,
                communityName: '华润中央公园',
                status: 1,
                statusName: '上架中',
                weights: 28.0,
                qrCode: 'https://res1.bnq.com.cn/FkDn-ZwmbaUZudGZaEpZrcRUX55i',
                designStyleList: [
                    {
                        id: 35,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:58.000+0000',
                        modifiedTime: '2020-12-17T09:27:58.000+0000',
                        deleted: false,
                        code: 'tc31002',
                        name: '现代',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 35,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: null,
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/FrPJyOVkDwVsW6vRgMP717d4sXWR',
                readCount: 181,
                shareCount: 183,
                keyword: '666',
                imgWidth: 1280,
                imgHeight: 645,
            },
            {
                id: 9,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-13 16:59:11',
                modifiedTime: '2021-01-20 10:49:02',
                deleted: false,
                number: '00009',
                designerCode: 'DN_2021011300004',
                designerName: '黎剑锋',
                designerHeadImg: 'https://res1.bnq.com.cn/597bfc9246c540b2b96a36a7596bb4ce.jpg',
                caseTitle: '500+㎡三层别墅重塑现代居住质感',
                serviceType: 'DST10003',
                serviceTypeName: '全案设计',
                caseHouseType: '1006',
                caseHouseTypeName: '别墅',
                room: 3,
                hall: 3,
                kitchen: 1,
                toilet: 3,
                caseSize: 530.0,
                designStyle: 'tc31002',
                caseCostType: null,
                totalCost: null,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11008',
                caseProvinceCode: '330000',
                caseProvinceName: '浙江',
                caseCityCode: '330600',
                caseCityName: '绍兴',
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 25.0,
                qrCode: 'https://res1.bnq.com.cn/FvGoZ-7C-WVBiz5Y1B5WGQNnTFZq',
                designStyleList: [
                    {
                        id: 35,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:58.000+0000',
                        modifiedTime: '2020-12-17T09:27:58.000+0000',
                        deleted: false,
                        code: 'tc31002',
                        name: '现代',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 35,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 9,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:08.000+0000',
                        modifiedTime: '2020-12-17T09:22:08.000+0000',
                        deleted: false,
                        code: 'tc11008',
                        name: '中年夫妻',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 9,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/79ad3c0fbafe452ea1b02f3e320014a0.JPG',
                readCount: 2,
                shareCount: 2,
                keyword: null,
                imgWidth: 3389,
                imgHeight: 3000,
            },
            {
                id: 4,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-13 15:04:33',
                modifiedTime: '2021-01-20 10:51:53',
                deleted: false,
                number: '00004',
                designerCode: 'DN_2021011300001',
                designerName: '韩蒙梦',
                designerHeadImg: 'https://res1.bnq.com.cn/8826668926124391ad9f9beff3163105.jpg',
                caseTitle: '超显大92㎡小户型，高级配色眼红到爆炸！',
                serviceType: 'DST10001',
                serviceTypeName: '硬装设计',
                caseHouseType: '1002',
                caseHouseTypeName: '两室',
                room: 2,
                hall: 1,
                kitchen: 1,
                toilet: 1,
                caseSize: 92.0,
                designStyle: 'tc31001',
                caseCostType: null,
                totalCost: null,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11015',
                caseProvinceCode: '110000',
                caseProvinceName: '北京',
                caseCityCode: '110000',
                caseCityName: null,
                communityName: '华纺易城',
                status: 1,
                statusName: '上架中',
                weights: 25.0,
                qrCode: 'https://res1.bnq.com.cn/FjU9N1aMgTRAIefILx8ilqXm2xJT',
                designStyleList: [
                    {
                        id: 34,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:57.000+0000',
                        modifiedTime: '2020-12-17T09:27:57.000+0000',
                        deleted: false,
                        code: 'tc31001',
                        name: '北欧',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 34,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 16,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:09.000+0000',
                        modifiedTime: '2020-12-17T09:22:09.000+0000',
                        deleted: false,
                        code: 'tc11015',
                        name: '都市白领',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 16,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/FlGjPZSGBMBlWB2Cr-fMXX-eLsIh',
                readCount: 2,
                shareCount: 3,
                keyword: null,
                imgWidth: 1197,
                imgHeight: 1000,
            },
            {
                id: 77,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-26 17:43:05',
                modifiedTime: '2021-01-26 17:43:05',
                deleted: false,
                number: '00077',
                designerCode: 'DN_2021012600023',
                designerName: '何鑫晶',
                designerHeadImg: 'https://res1.bnq.com.cn/FhGSBFgQUvj0YH6HJavAjm6SHEp3',
                caseTitle: '117㎡现代住宅，大道至简，返璞归真！',
                serviceType: 'DST10001',
                serviceTypeName: '硬装设计',
                caseHouseType: '1003',
                caseHouseTypeName: '三室',
                room: 3,
                hall: 2,
                kitchen: 1,
                toilet: 2,
                caseSize: 117.0,
                designStyle: 'tc31002',
                caseCostType: 1,
                totalCost: 20.0,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11002',
                caseProvinceCode: '120000',
                caseProvinceName: '天津',
                caseCityCode: '120000',
                caseCityName: null,
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 1.0,
                qrCode: 'https://res1.bnq.com.cn/FoeSM58PY3fidJgXwJZmyJeoG7_z',
                designStyleList: [
                    {
                        id: 35,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:58.000+0000',
                        modifiedTime: '2020-12-17T09:27:58.000+0000',
                        deleted: false,
                        code: 'tc31002',
                        name: '现代',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 35,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 3,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:07.000+0000',
                        modifiedTime: '2020-12-17T09:22:07.000+0000',
                        deleted: false,
                        code: 'tc11002',
                        name: '家有宝宝',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 3,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/FgTg9Agnh7ni6SUZLBTJy0sfuUTk',
                readCount: 72,
                shareCount: 72,
                keyword: null,
                imgWidth: 1000,
                imgHeight: 666,
            },
            {
                id: 30,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-15 10:11:43',
                modifiedTime: '2021-01-15 10:11:44',
                deleted: false,
                number: '00030',
                designerCode: 'DN_2021011300006',
                designerName: '赵刘建',
                designerHeadImg: 'https://res1.bnq.com.cn/f50837aee0b944fe88b958787cdc5351.jpg',
                caseTitle: '简约与诗意相得益彰 ，生活调性不再刻意',
                serviceType: 'DST10003',
                serviceTypeName: '全案设计',
                caseHouseType: '1004',
                caseHouseTypeName: '四室',
                room: 4,
                hall: 2,
                kitchen: 1,
                toilet: 2,
                caseSize: 148.0,
                designStyle: 'tc31002,tc31005',
                caseCostType: null,
                totalCost: null,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11018',
                caseProvinceCode: '310000',
                caseProvinceName: '上海',
                caseCityCode: '310000',
                caseCityName: null,
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 1.0,
                qrCode: 'https://res1.bnq.com.cn/Fscn5EmZHvCWZCZW13TYBJ41uH-Q',
                designStyleList: [
                    {
                        id: 35,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:58.000+0000',
                        modifiedTime: '2020-12-17T09:27:58.000+0000',
                        deleted: false,
                        code: 'tc31002',
                        name: '现代',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 35,
                    },
                    {
                        id: 38,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:59.000+0000',
                        modifiedTime: '2020-12-17T09:27:59.000+0000',
                        deleted: false,
                        code: 'tc31005',
                        name: '中式',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 38,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 19,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:09.000+0000',
                        modifiedTime: '2020-12-17T09:22:09.000+0000',
                        deleted: false,
                        code: 'tc11018',
                        name: '工薪一族',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 19,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/f64d45fa640341ec8c19d8fb3f68fdbb.jpg',
                readCount: 26,
                shareCount: 26,
                keyword: null,
                imgWidth: 1800,
                imgHeight: 2634,
            },
            {
                id: 22,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-14 13:43:28',
                modifiedTime: '2021-01-20 10:20:04',
                deleted: false,
                number: '00022',
                designerCode: 'DN_2021011300003',
                designerName: '王穆紘',
                designerHeadImg: 'https://res1.bnq.com.cn/8dfdbae17ce64421a8637187cae98d41.jpg',
                caseTitle: '63㎡开放式设计，功能储物翻倍！',
                serviceType: 'DST10001',
                serviceTypeName: '硬装设计',
                caseHouseType: '1002',
                caseHouseTypeName: '两室',
                room: 2,
                hall: 1,
                kitchen: 1,
                toilet: 1,
                caseSize: 63.0,
                designStyle: 'tc31001',
                caseCostType: null,
                totalCost: null,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21002',
                ownerImage: 'tc11001',
                caseProvinceCode: '310000',
                caseProvinceName: '上海',
                caseCityCode: '310000',
                caseCityName: null,
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 0.0,
                qrCode: 'https://res1.bnq.com.cn/FuHuZiTTMA9gbwHg42sZvGndu7cj',
                designStyleList: [
                    {
                        id: 34,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:57.000+0000',
                        modifiedTime: '2020-12-17T09:27:57.000+0000',
                        deleted: false,
                        code: 'tc31001',
                        name: '北欧',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 34,
                    },
                ],
                caseTypeList: [
                    {
                        id: 22,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21002',
                        name: '老房翻新',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 22,
                    },
                ],
                ownerImageList: [
                    {
                        id: 2,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:07.000+0000',
                        modifiedTime: '2020-12-17T09:22:07.000+0000',
                        deleted: false,
                        code: 'tc11001',
                        name: '二人世界',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 2,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/cb622597ce5745efadc40c168e1eec0c.jpg',
                readCount: 0,
                shareCount: 0,
                keyword: null,
                imgWidth: 2003,
                imgHeight: 1336,
            },
            {
                id: 67,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-22 09:15:09',
                modifiedTime: '2021-01-22 09:23:14',
                deleted: false,
                number: '00067',
                designerCode: 'DN_2021011800011',
                designerName: '何柳',
                designerHeadImg: 'https://res1.bnq.com.cn/FiQ80XJNBP0n7zyHg3CjUONuOW6v',
                caseTitle: '120㎡满满粉色系现代Ins风住宅设计',
                serviceType: 'DST10001',
                serviceTypeName: '硬装设计',
                caseHouseType: '1003',
                caseHouseTypeName: '三室',
                room: 3,
                hall: 2,
                kitchen: 1,
                toilet: 2,
                caseSize: 120.0,
                designStyle: 'tc31001,tc31002',
                caseCostType: 1,
                totalCost: 20.0,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11002',
                caseProvinceCode: '110000',
                caseProvinceName: '北京',
                caseCityCode: '110000',
                caseCityName: '北京',
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 0.0,
                qrCode: null,
                designStyleList: [
                    {
                        id: 34,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:57.000+0000',
                        modifiedTime: '2020-12-17T09:27:57.000+0000',
                        deleted: false,
                        code: 'tc31001',
                        name: '北欧',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 34,
                    },
                    {
                        id: 35,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:58.000+0000',
                        modifiedTime: '2020-12-17T09:27:58.000+0000',
                        deleted: false,
                        code: 'tc31002',
                        name: '现代',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 35,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 3,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:07.000+0000',
                        modifiedTime: '2020-12-17T09:22:07.000+0000',
                        deleted: false,
                        code: 'tc11002',
                        name: '家有宝宝',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 3,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/Fn849WQHe9GB8PUltosUUovO0TCm',
                readCount: 3,
                shareCount: 3,
                keyword: null,
                imgWidth: 4000,
                imgHeight: 3000,
            },
            {
                id: 11,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-13 17:16:58',
                modifiedTime: '2021-01-20 10:47:04',
                deleted: false,
                number: '00011',
                designerCode: 'DN_2021011300009',
                designerName: '袁原',
                designerHeadImg: 'https://res1.bnq.com.cn/acfa1f13ad3b451ea5a366e34d90073c.jpg',
                caseTitle: '160㎡现代空间，质朴优雅的静态美',
                serviceType: 'DST10001',
                serviceTypeName: '硬装设计',
                caseHouseType: '1003',
                caseHouseTypeName: '三室',
                room: 3,
                hall: 2,
                kitchen: 1,
                toilet: 2,
                caseSize: 160.0,
                designStyle: 'tc31002',
                caseCostType: 1,
                totalCost: 42.0,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11005',
                caseProvinceCode: '110000',
                caseProvinceName: '北京',
                caseCityCode: '110000',
                caseCityName: null,
                communityName: null,
                status: 1,
                statusName: '上架中',
                weights: 0.0,
                qrCode: 'https://res1.bnq.com.cn/FkprrEim4ghiLuPyygUk25YqzkpQ',
                designStyleList: [
                    {
                        id: 35,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:58.000+0000',
                        modifiedTime: '2020-12-17T09:27:58.000+0000',
                        deleted: false,
                        code: 'tc31002',
                        name: '现代',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 35,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 6,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:07.000+0000',
                        modifiedTime: '2020-12-17T09:22:07.000+0000',
                        deleted: false,
                        code: 'tc11005',
                        name: '三代同堂',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 6,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/948c854dff1c4fa98fc9a957d69b3298.jpg',
                readCount: 1,
                shareCount: 1,
                keyword: null,
                imgWidth: 3840,
                imgHeight: 2160,
            },
            {
                id: 19,
                creatorId: 0,
                lastModifierId: 0,
                createTime: '2021-01-14 11:39:24',
                modifiedTime: '2021-01-20 10:21:22',
                deleted: false,
                number: '00019',
                designerCode: 'DN_2021011300002',
                designerName: '郝永刚',
                designerHeadImg: 'https://res1.bnq.com.cn/43067d49719345fcbdf7c53c4b17cf6a.jpg',
                caseTitle: '80㎡自然色调打造90后夫妻的美丽新居',
                serviceType: 'DST10001',
                serviceTypeName: '硬装设计',
                caseHouseType: '1002',
                caseHouseTypeName: '两室',
                room: 2,
                hall: 2,
                kitchen: 1,
                toilet: 2,
                caseSize: 80.0,
                designStyle: 'tc31001',
                caseCostType: 1,
                totalCost: 25.0,
                designCost: null,
                hardCost: null,
                softCost: null,
                caseType: 'tc21001',
                ownerImage: 'tc11001',
                caseProvinceCode: '110000',
                caseProvinceName: '北京',
                caseCityCode: '110000',
                caseCityName: null,
                communityName: '金鼎佳苑',
                status: 1,
                statusName: '上架中',
                weights: 0.0,
                qrCode: 'https://res1.bnq.com.cn/Fgnf48s3tvPnddL7MdxxFycGhGLv',
                designStyleList: [
                    {
                        id: 34,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:27:57.000+0000',
                        modifiedTime: '2020-12-17T09:27:57.000+0000',
                        deleted: false,
                        code: 'tc31001',
                        name: '北欧',
                        parentCode: 'tp30001',
                        level: 2,
                        sort: 34,
                    },
                ],
                caseTypeList: [
                    {
                        id: 21,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:25:23.000+0000',
                        modifiedTime: '2020-12-17T09:25:23.000+0000',
                        deleted: false,
                        code: 'tc21001',
                        name: '新房装修',
                        parentCode: 'tp20001',
                        level: 2,
                        sort: 21,
                    },
                ],
                ownerImageList: [
                    {
                        id: 2,
                        creatorId: 0,
                        lastModifierId: 0,
                        createTime: '2020-12-17T09:22:07.000+0000',
                        modifiedTime: '2020-12-17T09:22:07.000+0000',
                        deleted: false,
                        code: 'tc11001',
                        name: '二人世界',
                        parentCode: 'tp10001',
                        level: 2,
                        sort: 2,
                    },
                ],
                designerVO: null,
                coverImg: 'https://res1.bnq.com.cn/96796354b8d74c1baae757ad9d999d42.jpg',
                readCount: 0,
                shareCount: 0,
                keyword: null,
                imgWidth: 1499,
                imgHeight: 1000,
            },
        ],
        prePage: 0,
        nextPage: 2,
        isFirstPage: true,
        isLastPage: false,
        hasPreviousPage: false,
        hasNextPage: true,
        navigatePages: 8,
        navigatepageNums: [1, 2, 3, 4, 5],
        navigateFirstPage: 1,
        navigateLastPage: 5,
        firstPage: 1,
        lastPage: 5,
    },
    meta: null,
    success: true,
    timestampDate: '2021-03-08 10:17:46',
};
